### ISSUE TITLE
Broken Build Process

### ISSUE THREAD

**Issue by BadHabbits1337** [chigraph/chigraph-gui#20]
I'm trying to build ChigraphGui on windows with msvc 2017, it builds but i cant start it because of incompatibility KF5 and Qt version, because KF5IconThemes.dll doesn't contains entry point for "??4QIconEngine@@QEAAAEAV0@AEBV0@@Z". I have Qt 5.12 installed and add it to PATH.
Also i've got a lots of problems while i trying to build it, like invalid arguments for compiler "/Wno-error=parentheses".
Is there any chance to get commit with fixes, or just builded binaries, cause i'm realy frustrated

**Comment by BadHabbits1337** [comment]
Well, finally i've made it running. I build it with qt 5.7, and it works, kind of.
Theme on windows is broken, i have some faults on some menu items, like about, help etc...

**Comment by russelltg** [comment]
Yeah building it on windows is definitely a pain in the ass. I should have built binaries, but have more or less abandoned the project as I have become super busy. Pull requests are welcome, and it's possible I'll pick it up at a later date. 

Sorry about that :(.
